name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: Andrius-Anselmi
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
